
name: perfect_keto
version: '1.0'
profile: perfect_keto
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]


on-run-end: 
    - "grant usage on schema {{target.schema}} to role REPORTER"
    - "grant usage on schema {{target.schema}} to role LOADER"
    
models:
    post-hook: "grant select on {{this}} to role REPORTER"
    
target-path: "target"  
clean-targets:
    - "target"
    - "dbt_modules"