
name: perfect_keto
version: '1.0'
profile: perfect_keto
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]


on-run-start:
    - "{{resume_warehouse(var('resume_warehouse', false), var('warehouse_name'))}}"    

on-run-end: 
    - "{{suspend_warehouse(var('suspend_warehouse', false), var('warehouse_name'))}}"
    - "grant usage on schema {{target.schema}} to role REPORTER"
    - "grant usage on schema {{target.schema}} to role LOADER"
    
models:
    post-hook: "grant select on {{this}} to role REPORTER"
    vars:
        warehouse_name: 'LOADING'
        addresses_table: stg_shopify_customers
        customers_table: stg_shopify_customers
        order_items_table: stg_shopify_order_items
        orders_table: stg_shopify_orders
        products_table: stg_shopify_products
        customer_aggregate_on: customer_id
        customer_join_on: customer_id        
    
target-path: "target"  
clean-targets:
    - "target"
    - "dbt_modules"