
name: perfect_keto
version: '1.0'
profile: perfect_keto
source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]


on-run-start:
    - "{{resume_warehouse(var('resume_warehouse', false), var('warehouse_name'))}}"    

on-run-end: 
    - "{{suspend_warehouse(var('suspend_warehouse', false), var('warehouse_name'))}}"
    - "grant usage on schema {{target.schema}} to role REPORTER"
    - "grant usage on schema {{target.schema}} to role LOADER"
    
models:
    post-hook: "grant select on {{this}} to role REPORTER"
    fishtown_analytics_ecommerce:
      transform:
        addresses:
          enabled: false

    vars:
        warehouse_name: 'LOADING'
        addresses_table: "not using this"
        customers_table: "{{ ref('stg_shopify_customers') }}"
        order_items_table: "{{ ref('stg_shopify_order_items') }}"
        orders_table: "{{ ref('stg_shopify_orders') }}"
        products_table: "{{ ref('stg_shopify_products') }}"
        customer_aggregate_on: customer_id
        customer_join_on: customer_id
        
    snowplow:
        vars:
            snowplow:timezone: 'America/New_York'
            snowplow:page_ping_frequency: 10
            snowplow:events: "{{ ref('stg_events') }}"
            snowplow:context:web_page: "{{ ref('stg_web_page_context')}}"
            snowplow:context:performance_timing: false
            snowplow:context:useragent: false
    base:
      optional:
        enabled: false
    page_views:
      optional:
        enabled: false               
    perfect_keto:
        
target-path: "target"  
clean-targets:
    - "target"
    - "dbt_modules"