
version: 2

models:
    - name: snowplow_sessions_final
      description: '{{ doc("snowplow_sessions") }}'
      
      columns:
          - name: session_id
            description: A visit / session identifier
            tests:
                - not_null
                - unique