version: 2

version: 2

models:
    
    - name: snowplow_sessions__gclids
      columns:
          - name: unique_id
            tests:
                - not_null
                - unique

    - name: snowplow_sessions__mapped
      columns:
          - name: session_id
            description: A visit / session identifier
            tests:
                - not_null
                - unique

    - name: snowplow_sessions__with_channels
      columns: 
          - name: session_id
            tests:
                - relationships:
                    field: session_id
                    to: ref('snowplow_sessions')
